version: '3.8'

services:
  backend:
    image: amandeeptruinc/order-manage-app-backend:v1.0.4
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres-db-service
    restart: on-failure

  postgres-db-service:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    depends_on:
      - postgres-db-service
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  postgres_data:
